[project]
name = "geidea_erpgulf"
authors = [
    { name = "ERPGulf", email = "support@erpgulf.com"}
]
description = "geidea_erpgulf"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "paho-mqtt>=1.6.1"
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[[tool.bench.dev-dependencies]]
# package_name = "~=1.1.0"